import { useCallback, useEffect, useState } from 'react';
import { api, formatDate, themeFromFields } from './api';
import Preview from './Preview';
import StoreAccounts from './StoreAccounts';
import ThemeEditor from './ThemeEditor';
import { Alert, Icon, Pill, Status, StoreLogo } from './ui';

const STORE_FOR_PLATFORM = { ANDROID: 'GOOGLE_PLAY', IOS: 'APPLE' };
const STORE_NAME = { GOOGLE_PLAY: 'Google Play', APPLE: 'Apple' };
const PLATFORM = { ANDROID: { label: 'Android', store: 'Google Play' }, IOS: { label: 'iOS', store: 'App Store' } };
const ENVIRONMENT = {
  DEVELOPMENT: 'Internal build for your team to try.',
  STAGE: 'Test build for testers before going live.',
  PRODUCTION: 'The version customers download from the store.',
};
const ACCOUNT_STATUS = {
  INVITE_SENT: ['warning', 'Waiting for Pallet'],
  VERIFIED: ['success', 'Access confirmed'],
  FAILED: ['danger', 'Needs attention'],
};

const NEW = 'new';
// Merchants give only what they know: the app's name and which store it sells from.
// Technical IDs (app key, package name, bundle ID, deep link) are generated by Pallet.
const emptyDetails = branchId => ({ appName: '', defaultBranchId: branchId });

const validateDetails = details => {
  const errors = {};
  const name = (details.appName || '').trim();
  if (!name) errors.appName = 'Enter the app name';
  else if (name.length > 30) errors.appName = 'At most 30 characters';
  if (!(details.defaultBranchId || '').trim()) errors.defaultBranchId = 'Choose a store';
  return errors;
};

const accountsReady = list => list.some(a => ['INVITE_SENT', 'VERIFIED'].includes(a.status));

function Stepper({ steps, current, onSelect }) {
  return (
    <ol className="stepper">
      {steps.map((step, index) => {
        const state = index === current ? 'current' : step.state;
        return (
          <li key={step.key} className={`stepper-item ${state}`}>
            <button type="button" disabled={step.locked} onClick={() => onSelect(index)} aria-current={index === current ? 'step' : undefined}>
              <span className="stepper-dot">
                {step.state === 'done' && index !== current ? <Icon name="check" size={14} />
                  : step.state === 'waiting' && index !== current ? <Icon name="clock" size={14} />
                    : step.state === 'problem' && index !== current ? '!' : index + 1}
              </span>
              <span className="stepper-text"><b>{step.title}</b><small>{step.hint}</small></span>
            </button>
          </li>
        );
      })}
    </ol>
  );
}

function DropZone({ id, label, rules, imageUrl, imageClass, busy, onFile }) {
  const [over, setOver] = useState(false);
  return (
    <label htmlFor={id} className={`dropzone ${over ? 'over' : ''} ${imageUrl ? 'has-image' : ''}`}
      onDragOver={e => { e.preventDefault(); setOver(true); }}
      onDragLeave={() => setOver(false)}
      onDrop={e => { e.preventDefault(); setOver(false); onFile(e.dataTransfer.files[0]); }}>
      <input id={id} type="file" accept="image/png,image/jpeg" className="visually-hidden" onChange={e => { onFile(e.target.files[0]); e.target.value = ''; }} />
      {imageUrl ? <img className={imageClass} src={imageUrl} alt={label} /> : <span className="dropzone-icon"><Icon name="upload" size={22} /></span>}
      <span className="dropzone-text">
        <b>{label}</b>
        <small>{busy ? 'Uploading…' : imageUrl ? 'Click or drop a new image to replace it' : 'Click to upload or drag and drop'}</small>
        <small className="muted">{rules}</small>
      </span>
    </label>
  );
}

export default function AppBuilder({ meta, settings, user, openBuilds }) {
  const [apps, setApps] = useState([]);
  const [appId, setAppId] = useState(NEW);
  const [app, setApp] = useState(null);
  const [details, setDetails] = useState(emptyDetails(settings.branchId));
  const [theme, setTheme] = useState(() => themeFromFields(meta.themeFields, null));
  const [release, setRelease] = useState({ platform: 'ANDROID', environment: 'STAGE', artifactType: 'AAB', versionName: '1.0.0' });
  const [busy, setBusy] = useState('');
  const [status, setStatus] = useState({});
  const [attempted, setAttempted] = useState(false);
  const [accounts, setAccounts] = useState([]);
  const [onboarding, setOnboarding] = useState(null);
  const [access, setAccess] = useState(null);
  const [stores, setStores] = useState([]);
  const [step, setStep] = useState(0);

  useEffect(() => {
    let active = true;
    api.stores(settings.retailId).then(list => active && setStores(list)).catch(() => active && setStores([]));
    return () => { active = false; };
  }, [settings.retailId]);

  // Keep the app's current store selectable even if it is missing from the list.
  const storeOptions = details.defaultBranchId && !stores.some(s => s.branchId === details.defaultBranchId)
    ? [...stores, { branchId: details.defaultBranchId, branchName: details.defaultBranchId }]
    : stores;

  const say = (section, text, error = false) => setStatus(current => ({ ...current, [section]: { text, error } }));

  const fetchLaunchSetup = useCallback(
    () => Promise.all([api.storeAccounts(settings.retailId), api.onboarding(settings.retailId)]),
    [settings.retailId]);

  const loadAccounts = useCallback(async () => {
    try {
      const [list, checklist] = await fetchLaunchSetup();
      setAccounts(list);
      setOnboarding(checklist);
    } catch (error) {
      say('apps', error.message, true);
    }
  }, [fetchLaunchSetup]);

  useEffect(() => {
    let active = true;
    fetchLaunchSetup()
      .then(([list, checklist]) => {
        if (!active) return;
        setAccounts(list);
        setOnboarding(checklist);
        // Merchants who already invited Pallet start at the app details.
        if (accountsReady(list)) setStep(current => (current === 0 ? 1 : current));
      })
      .catch(error => active && say('apps', error.message, true));
    return () => { active = false; };
  }, [fetchLaunchSetup]);

  // Industry-standard gates: create and test builds once Pallet is invited (or confirmed);
  // production only after access is confirmed.
  const gateOn = meta.storeAccounts?.required !== false;
  const statusOf = storeType => accounts.find(a => a.storeType === storeType)?.status;
  const connected = storeType => ['INVITE_SENT', 'VERIFIED'].includes(statusOf(storeType));
  const canCreate = !gateOn || accountsReady(accounts);
  const publishStore = STORE_FOR_PLATFORM[release.platform];
  const production = release.environment === 'PRODUCTION';
  const canPublish = !gateOn || (production ? statusOf(publishStore) === 'VERIFIED' : connected(publishStore));

  const loadApps = useCallback(async () => {
    try {
      setApps(await api.listApps(settings.retailId));
    } catch (error) {
      say('apps', error.message, true);
    }
  }, [settings.retailId]);

  useEffect(() => {
    let active = true;
    api.listApps(settings.retailId)
      .then(list => active && setApps(list))
      .catch(error => active && say('apps', error.message, true));
    return () => { active = false; };
  }, [settings.retailId]);

  const showApp = loaded => {
    setApp(loaded);
    setDetails({ appName: loaded.appName, defaultBranchId: loaded.defaultBranchId });
    setTheme(themeFromFields(meta.themeFields, loaded.theme));
  };

  const selectApp = async id => {
    setAppId(id);
    setStatus({});
    setAttempted(false);
    setAccess(null);
    if (id === NEW) {
      setApp(null);
      setDetails(emptyDetails(settings.branchId));
      setTheme(themeFromFields(meta.themeFields, null));
      setStep(canCreate ? 1 : 0);
      return;
    }
    try {
      showApp(await api.getApp(id));
      setStep(current => (current === 0 ? 1 : current));
    } catch (error) {
      say('apps', error.message, true);
    }
  };

  const run = async (section, action) => {
    setBusy(section);
    try {
      await action();
    } catch (error) {
      say(section, error.message, true);
    } finally {
      setBusy('');
    }
  };

  const detailErrors = validateDetails(details);
  const hasDetailErrors = Object.keys(detailErrors).length > 0;

  const saveDetails = event => {
    event?.preventDefault();
    setAttempted(true);
    if (hasDetailErrors) {
      say('details', 'Fix the highlighted fields first.', true);
      return;
    }
    submitDetails();
  };

  const submitDetails = () => run('details', async () => {
    const body = { appName: details.appName.trim(), defaultBranchId: details.defaultBranchId.trim() };
    if (!app) {
      const created = await api.createApp({ ...body, retailId: settings.retailId }, user);
      showApp(created);
      setAppId(created.appId);
      await loadApps();
      say('details', null);
      say('branding', `${created.appName} is created. Next, add the app icon and splash screen.`);
      setStep(2);
    } else {
      showApp(await api.updateApp(app.appId, body, user));
      await loadApps();
      say('details', 'Details saved.');
    }
  });

  const upload = (assetType, file) => file && run(assetType, async () => {
    showApp(await api.uploadAsset(app.appId, assetType, file, user));
    say('branding', assetType === 'ICON' ? 'Icon uploaded (stored as 1024×1024 PNG).' : 'Splash screen uploaded.');
  });

  const saveTheme = () => run('theme', async () => {
    showApp(await api.saveTheme(app.appId, theme, user));
    say('theme', 'Draft saved. The app keeps the published theme until you publish.');
  });

  const publishTheme = () => run('theme', async () => {
    await api.saveTheme(app.appId, theme, user);
    const published = await api.publishTheme(app.appId, user);
    showApp(await api.getApp(app.appId));
    say('theme', `Theme v${published.themeVersion} is live. Apps pick it up the next time they open.`);
  });

  const publishBuild = () => run('release', async () => {
    const build = await api.createBuild(app.appId, release, user);
    showApp(await api.getApp(app.appId));
    say('release', `Build ${build.buildId} is ${build.status.toLowerCase()}. ${build.statusMessage || ''}`);
  });

  const checkAccess = () => run('release', async () => {
    setAccess(await api.storeAccess(app.appId, release.platform));
  });

  const deleteApp = () => {
    if (!window.confirm(`Delete ${app.appName}? The app is hidden from the App Builder.`)) return;
    run('apps', async () => {
      await api.deleteApp(app.appId, user);
      await loadApps();
      await selectApp(NEW);
      say('apps', 'App deleted.');
    });
  };

  const locked = Boolean(app?.identityLocked);
  const artifactTypes = meta.enums.artifactTypes[release.platform];
  const setupState = { READY: 'done', WAITING_FOR_PALLET: 'waiting', NEEDS_ATTENTION: 'problem' }[onboarding?.stage] || (canCreate ? 'waiting' : 'todo');
  const steps = [
    { key: 'setup', title: 'Launch setup', hint: 'Store accounts', icon: 'store', state: setupState,
      description: 'Your app is published under your own Google Play and Apple accounts. Invite Pallet as a team member; Pallet confirms access so your app can go live. You can design the app and run test builds while you wait.' },
    { key: 'details', title: 'App details', hint: 'Name and store', icon: 'phone', state: app ? 'done' : 'todo',
      description: 'Name your app and choose the store it sells from. Pallet creates the store IDs for you.' },
    { key: 'branding', title: 'Branding', hint: 'Icon and splash', icon: 'image', state: app?.iconUrl && app?.splashUrl ? 'done' : 'todo', locked: !app,
      description: 'Add the icon customers tap and the screen they see while the app opens.' },
    { key: 'theme', title: 'Theme', hint: 'Colors and style', icon: 'palette', state: app?.themeUrl ? 'done' : 'todo', locked: !app,
      description: 'Match the app to your brand. Theme changes go live without a new app release.' },
    { key: 'publish', title: 'Publish', hint: 'Build and release', icon: 'rocket', state: locked ? 'done' : 'todo', locked: !app,
      description: 'Build a new app version. Needed for a new icon, splash screen or app name.' },
  ];
  const doneCount = steps.filter(s => s.state === 'done').length;
  const currentStep = steps[step];
  const nextLocked = step < steps.length - 1 && steps[step + 1].locked;

  const fieldError = key => (attempted || (details[key] || '').trim()) ? detailErrors[key] : null;
  const platformCard = platform => {
    const storeType = STORE_FOR_PLATFORM[platform];
    const [tone, label] = ACCOUNT_STATUS[statusOf(storeType)] || ['neutral', 'Not connected'];
    return (
      <label key={platform} htmlFor={`platform-${platform}`} className={`choice-card ${release.platform === platform ? 'selected' : ''}`}>
        <input id={`platform-${platform}`} type="radio" name="platform" className="visually-hidden" checked={release.platform === platform}
          onChange={() => { setRelease({ ...release, platform, artifactType: meta.enums.artifactTypes[platform][0] }); setAccess(null); }} />
        <StoreLogo storeType={platform} />
        <span><b>{PLATFORM[platform].label}</b><small>{PLATFORM[platform].store}</small></span>
        <Pill tone={tone}>{label}</Pill>
      </label>
    );
  };

  return (
    <div className="builder">
      <div className="builder-main">
        <div className="app-bar card">
          <div className="app-bar-identity">
            {app?.iconUrl ? <img src={app.iconUrl} alt="" className="app-avatar" /> : <span className="app-avatar placeholder"><Icon name="phone" /></span>}
            <div>
              <b>{app ? app.appName : 'New app'}</b>
              <small>{app ? `${app.merchantKey} · ${doneCount} of ${steps.length} steps done` : `Retail ${settings.retailId}`}</small>
            </div>
          </div>
          <div className="app-bar-actions">
            <label htmlFor="app-picker" className="visually-hidden">Choose an app</label>
            <select id="app-picker" value={appId} onChange={e => selectApp(e.target.value)}>
              <option value={NEW}>New app</option>
              {apps.map(item => <option key={item.appId} value={item.appId}>{item.appName}</option>)}
            </select>
            {app && <button type="button" className="btn btn-secondary" onClick={() => selectApp(NEW)}><Icon name="plus" size={16} /> New app</button>}
          </div>
        </div>
        <Status state={status.apps} />

        <Stepper steps={steps} current={step} onSelect={setStep} />

        <section className="card step-panel" aria-labelledby="step-title">
          <header className="step-header">
            <span className="step-badge"><Icon name={currentStep.icon} size={20} /></span>
            <div>
              <small className="eyebrow">Step {step + 1} of {steps.length}</small>
              <h2 id="step-title">{currentStep.title}</h2>
              <p>{currentStep.description}</p>
            </div>
          </header>

          {step === 0 && (
            <StoreAccounts meta={meta} retailId={settings.retailId} user={user} accounts={accounts} onboarding={onboarding} onChanged={loadAccounts} />
          )}

          {step === 1 && (
            <form className="stack" onSubmit={saveDetails} noValidate>
              {!app && !canCreate && (
                <Alert tone="warning" title="Invite Pallet first"
                  action={<button type="button" className="btn btn-secondary" onClick={() => setStep(0)}>Go to launch setup</button>}>
                  Invite Pallet to your Google Play or Apple account before creating the app.
                </Alert>
              )}
              <div className="form-grid">
                <label htmlFor="details-appName" className="field">
                  <span className="field-label">App name</span>
                  <input id="details-appName" value={details.appName ?? ''} placeholder="Amma Store" maxLength={40}
                    className={fieldError('appName') ? 'invalid' : ''} aria-invalid={Boolean(fieldError('appName'))}
                    onChange={e => setDetails({ ...details, appName: e.target.value })} />
                  <span className="field-foot">
                    {fieldError('appName') ? <small className="field-error">{fieldError('appName')}</small>
                      : <small>Shown under the app icon and in the stores.</small>}
                    <small className={details.appName.length > 30 ? 'field-error' : ''}>{details.appName.length}/30</small>
                  </span>
                </label>
                <label htmlFor="details-store" className="field">
                  <span className="field-label">Store the app sells from</span>
                  <select id="details-store" value={details.defaultBranchId || ''}
                    className={attempted && detailErrors.defaultBranchId ? 'invalid' : ''}
                    onChange={e => setDetails({ ...details, defaultBranchId: e.target.value })}>
                    <option value="">Choose a store</option>
                    {storeOptions.map(store => <option key={store.branchId} value={store.branchId}>{store.branchName}</option>)}
                  </select>
                  {attempted && detailErrors.defaultBranchId
                    ? <small className="field-error">{detailErrors.defaultBranchId}</small>
                    : <small>Customers see this store's products first. They can switch stores in the app.</small>}
                </label>
              </div>

              {app && (
                <div className="info-panel">
                  <div className="info-panel-head">
                    <b>Store listing IDs</b>
                    <Pill tone={locked ? 'neutral' : 'info'}>{locked ? 'Locked after first build' : 'Fixed after the first build'}</Pill>
                  </div>
                  <dl className="facts">
                    <div><dt>App ID</dt><dd>{app.merchantKey}</dd></div>
                    <div><dt>Android package</dt><dd>{app.androidPackageName}</dd></div>
                    <div><dt>iOS bundle ID</dt><dd>{app.iosBundleId}</dd></div>
                    <div><dt>App link</dt><dd>{app.deepLinkScheme}://</dd></div>
                  </dl>
                  <small>Created by Pallet for your store listings.</small>
                </div>
              )}

              <div className="button-row">
                <button type="submit" className="btn btn-primary" disabled={busy === 'details' || (!app && !canCreate)}>
                  {busy === 'details' ? 'Saving…' : app ? 'Save details' : 'Create app'}
                </button>
              </div>
              <Status state={status.details} />

              {app && (
                <div className="danger-zone">
                  <div><b>Delete app</b><small>Hides the app from the App Builder. Refused while a build is running.</small></div>
                  <button type="button" className="btn btn-danger" disabled={busy === 'apps'} onClick={deleteApp}><Icon name="trash" size={16} /> Delete</button>
                </div>
              )}
            </form>
          )}

          {step === 2 && app && (
            <div className="stack">
              <div className="upload-grid">
                <DropZone id="icon-file" label="App icon" imageUrl={app.iconUrl} imageClass="icon-image" busy={busy === 'ICON'}
                  rules={`Square PNG or JPEG, ${meta.assetRules.ICON.minPixels}–${meta.assetRules.ICON.maxPixels} px`}
                  onFile={file => upload('ICON', file)} />
                <DropZone id="splash-file" label="Splash screen" imageUrl={app.splashUrl} imageClass="splash-image" busy={busy === 'SPLASH'}
                  rules={`PNG or JPEG, up to ${Math.round(meta.assetRules.SPLASH.maxBytes / 1048576)} MB`}
                  onFile={file => upload('SPLASH', file)} />
              </div>
              <Status state={status.ICON} />
              <Status state={status.SPLASH} />
              <Status state={status.branding} />
              <Alert tone="info">A new icon or splash screen reaches customers with the next app version (step 5).</Alert>
            </div>
          )}

          {step === 3 && app && (
            <div className="stack">
              <div className="live-bar">
                {app.themeUrl
                  ? <><Pill tone="success">Live v{app.themeVersion}</Pill><small>Published {formatDate(app.themePublishedAt)} · <a href={app.themeUrl} target="_blank" rel="noreferrer">theme file <Icon name="external" size={12} /></a></small></>
                  : <><Pill tone="neutral">Not published</Pill><small>The app uses Pallet's default theme until you publish.</small></>}
              </div>
              <ThemeEditor fields={meta.themeFields} theme={theme} onChange={setTheme} />
              <div className="sticky-actions">
                <small>Save a draft to keep working, or publish to update every installed app.</small>
                <div className="button-row">
                  <button type="button" className="btn btn-secondary" disabled={busy === 'theme'} onClick={saveTheme}>Save draft</button>
                  <button type="button" className="btn btn-primary" disabled={busy === 'theme'} onClick={publishTheme}>{busy === 'theme' ? 'Working…' : 'Publish theme'}</button>
                </div>
              </div>
              <Status state={status.theme} />
            </div>
          )}

          {step === 4 && app && (
            <div className="stack">
              <div>
                <span className="field-label">Platform</span>
                <div className="choice-grid">{meta.enums.platforms.map(platformCard)}</div>
              </div>
              <div>
                <span className="field-label">Release type</span>
                <div className="segmented" role="radiogroup" aria-label="Release type">
                  {meta.enums.environments.map(value => (
                    <button key={value} type="button" role="radio" aria-checked={release.environment === value}
                      className={release.environment === value ? 'selected' : ''} onClick={() => setRelease({ ...release, environment: value })}>
                      {value.charAt(0) + value.slice(1).toLowerCase()}
                    </button>
                  ))}
                </div>
                <small>{ENVIRONMENT[release.environment]}</small>
              </div>
              <div className="form-grid">
                <label htmlFor="release-artifact" className="field">
                  <span className="field-label">File type</span>
                  <select id="release-artifact" value={release.artifactType} onChange={e => setRelease({ ...release, artifactType: e.target.value })}>
                    {artifactTypes.map(value => <option key={value}>{value}</option>)}
                  </select>
                  <small>{release.artifactType === 'APK' ? 'Installs directly on a phone, for testing.' : 'Store upload format.'}</small>
                </label>
                <label htmlFor="release-version" className="field">
                  <span className="field-label">Version name</span>
                  <input id="release-version" value={release.versionName} placeholder="1.0.0" onChange={e => setRelease({ ...release, versionName: e.target.value })} />
                  <small>What customers see in the store, e.g. 1.2.0.</small>
                </label>
              </div>

              {!canPublish && (
                <Alert tone="warning" title={production && connected(publishStore) ? 'Waiting for Pallet to confirm access' : `Connect ${STORE_NAME[publishStore]} first`}
                  action={<button type="button" className="btn btn-secondary" onClick={() => setStep(0)}>Launch setup</button>}>
                  {production && connected(publishStore)
                    ? `Production needs Pallet to confirm access to your ${STORE_NAME[publishStore]} account. Test builds (Development, Stage) work meanwhile.`
                    : `Invite Pallet to your ${STORE_NAME[publishStore]} account first.`}
                </Alert>
              )}
              {production && canPublish && (
                <Alert tone="info" title="Create the app in your store account first">
                  Production builds need the app to exist in your {STORE_NAME[publishStore]} account with {release.platform === 'IOS' ? 'bundle ID' : 'package'}{' '}
                  <code>{release.platform === 'IOS' ? app.iosBundleId : app.androidPackageName}</code>. Then use <b>Check store access</b>.
                </Alert>
              )}
              {access && access.platform === release.platform && (
                <Alert tone={access.ready ? 'success' : 'danger'} title={access.ready ? 'Store access looks good' : 'Store access problem'}>{access.message}</Alert>
              )}

              <div className="summary">
                <div><small>App</small><b>{app.appName}</b></div>
                <div><small>Platform</small><b>{PLATFORM[release.platform].label}</b></div>
                <div><small>Release</small><b>{release.environment.charAt(0) + release.environment.slice(1).toLowerCase()}</b></div>
                <div><small>Version</small><b>{release.versionName || '—'}</b></div>
              </div>

              <div className="button-row">
                <button type="button" className="btn btn-primary" disabled={busy === 'release' || !canPublish} onClick={publishBuild}>
                  <Icon name="rocket" size={16} /> {busy === 'release' ? 'Publishing…' : 'Start build'}
                </button>
                <button type="button" className="btn btn-secondary" disabled={busy === 'release' || !canPublish} onClick={checkAccess}>Check store access</button>
                <button type="button" className="btn btn-ghost" onClick={openBuilds}>View builds <Icon name="right" size={16} /></button>
              </div>
              <Status state={status.release} />
            </div>
          )}

          {currentStep.locked && (
            <div className="locked-note"><Icon name="info" /> Create the app in step 2 first.</div>
          )}

          <footer className="step-footer">
            <button type="button" className="btn btn-ghost" disabled={step === 0} onClick={() => setStep(step - 1)}>
              <Icon name="left" size={16} /> Back
            </button>
            {step < steps.length - 1 && (
              <button type="button" className="btn btn-secondary" disabled={nextLocked} onClick={() => setStep(step + 1)}
                title={nextLocked ? 'Create the app first' : undefined}>
                Continue to {steps[step + 1].title} <Icon name="right" size={16} />
              </button>
            )}
          </footer>
        </section>
      </div>
      <Preview appName={details.appName} theme={theme} iconUrl={app?.iconUrl} splashUrl={app?.splashUrl} />
    </div>
  );
}
